# Groq Cloud Configuration
groq.api.key=${GROQ_API_KEY:}
groq.base-url=https://api.groq.com/openai/v1
groq.model-name=llama-3.3-70b-versatile

# Backend Proxy URL for CLI calls
cwsgit.backend.url=https://git-agent-zqsc.onrender.com/api/v1/generate-commit

# Clean logs for CLI execution
spring.main.banner-mode=off
logging.level.root=WARN