# Groq Cloud Configuration
groq.api.key=${GROQ_API_KEY:}
groq.base-url=https://api.groq.com/openai/v1
groq.model-name=llama-3.3-70b-versatile

# Backend Proxy URL for CLI calls (Use live Render URL)
cwsgit.backend.url=https://git-agent-zqsc.onrender.com/api/v1/generate-commit

# Disable web server mode by default so CLI runs instantly without Tomcat
spring.main.web-application-type=none